POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Felipe"
}

###
GET http://localhost:3333/products

###
PUT http://localhost:3333/products/eaf67202-a0d4-4423-94ba-0745a23c33c2
Content-Type: application/json

{
  "name": "Gabriel"
}
###
DELETE http://localhost:3333/products/